version: '3'
services:
  redis:
    image: redis
  superset:
    image: amancevice/superset:0.27.0
    restart: always
    depends_on:
      - redis
    environment:
      TZ: UTC
      SUPERSET_HOME: /etc/superset
    ports:
      - "8088:8088"
    volumes:
      - ./config.py:/etc/superset/superset_config.py
      - ./data:/var/lib/superset
    user: root
